# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/blk_mem/blk_mem.xci
# IP: The module: 'blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/blk_mem/blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/blk_mem/blk_mem.xci
# IP: The module: 'blk_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/blk_mem/blk_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
