# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
# IP: The module: 'system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8 || ORIG_REF_NAME==bd_d5b8} -quiet] -quiet

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] -quiet

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/bd_d5b8_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_g_inst_0 || ORIG_REF_NAME==bd_d5b8_g_inst_0} -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0_ooc.xdc

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8_ooc.xdc

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
# IP: The module: 'system_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8 || ORIG_REF_NAME==bd_d5b8} -quiet] -quiet

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] -quiet

# IP: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_1/bd_d5b8_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d5b8_g_inst_0 || ORIG_REF_NAME==bd_d5b8_g_inst_0} -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0_ooc.xdc

# XDC: e:/zynq_pl_acc/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8_ooc.xdc
