# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window.xci
# IP: The module: 'fifo_conv_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_conv_window'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_conv_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window.xci
# IP: The module: 'fifo_conv_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_conv_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_conv_window/fifo_conv_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_conv_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
