# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer.xci
# IP: The module: 'fifo_signal_transfer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer.xci
# IP: The module: 'fifo_signal_transfer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/github_repo/ZYNQ_PL_CONV/vivado_project/zynq_pl_acc_demo/zynq_pl_acc_demo.srcs/sources_1/ip/fifo_signal_transfer/fifo_signal_transfer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_signal_transfer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
